name: James Hale
bio: Infosec engineering leader who specializes in automation and cloud infrastructure.
description: Infosec engineering leader who specializes in automation and cloud infrastructure.
external-image: false
picture: assets/images/profile.jpg
resume: true
resume-external: true
resume-url: https://hale.dev/cv.pdf
url: https://hale.dev
permalink: /:title/
# analytics-google: 'UA-83291518-1'
bsky: hale.aero
linkedin: jamesmhale
github: jmhale
email: james@hale.dev
mastodon:
  username: halesec
  fediverse: infosec.exchange
authors:
    jameshale:
        name: James Hale
        bio: Infosec engineering leader who specializes in automation and cloud infrastructure.
        external-image: false
        picture: assets/images/profile.jpg
        bsky: hale.aero

width: normal
projects: true
about: true
# blog: https://halesec.com
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-mentions:
    base_url: https://github.com

include:
  - .well-known

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md
